[package]
name = "mydns"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
byteorder = "1.5.0"
clap = { version = "4.4.16", features = ["derive"] }
deku = "0.16.0"
pretty-hex = "0.4.1"
thiserror = "1.0.56"
