[package]
name = "bitfields"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
bitfield = "0.14.0"
derive_builder = "0.12.0"
serde = {version = "1.0.188", features = ["derive"] }
